databases:
  - name: postgrest-db
    plan: free
    databaseName: budgetapp
    user: budgetapp
    
services:
  - type: web
    plan: free
    name: postgres
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budgetapp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
